name: CI

on: push

jobs:
  changed_files:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2  # OR "2" -> To retrieve the preceding commit.
      - name: Get changed files
        shell: bash
        run: |
          git fetch origin main
          AFFECTED=$(git diff origin/main..HEAD --name-only -- tests-examples/)
          echo $AFFECTED
          components=(`echo ${AFFECTED}`)
          for s in "${!components[@]}"; do
              component=${arr[$s]#tests-examples/}
              components[$s]=${component%/*}/
          done

          FILES=${components[@]}
          echo $FILES