name: CI

on: push

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Get changed files
        shell: bash
        id: affected
        run: |
          git fetch origin main
          AFFECTED=$(git diff origin/main..HEAD --name-only -- tests-examples/)
          for i in "${#AFFECTED[@]}"; do
              FILE=${AFFECTED[$i]##tests-examples/}
              echo $FILE
              AFFECTED[$i]=${FILE%/*}
              echo $AFFECTED[$i]
          done
          echo $AFFECTED


