name: CI

on: push

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Get changed files
        shell: bash
        id: affected
        run: |
          git fetch origin main
          AFFECTED=$(git diff origin/main..HEAD --name-only -- tests-examples/)
          for i in $AFFECTED; do
              FILE=$i
              FILE=${FILE##tests-examples}
              FILE=${FILE%/*}
              echo "$FILE" >> "$GITHUB_OUTPUT"
          done
    outputs:
      affected: ${{steps.affected.outputs.FILE}}


