name: CI

on: workflow_dispatch

jobs:
  changed_files:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4

      - name: Get Changed Files
        id: changed_files
        run: |
          CHANGED_FILES=$(git diff --name-only main..HEAD)
          echo "::set-output name=changed_files::$CHANGED_FILES"

      - name: Display Changed Files
        run: echo ${{ steps.changed_files.outputs.changed_files }}