name: CI

on: push

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    outputs:
      affected: ${{ steps.affected.outputs.AFFECTED }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Get changed files
        shell: bash
        id: affected
        run: |
          git fetch origin main
          diff=$(git diff origin/main..HEAD --name-only -- tests-examples/)
          echo "AFFECTED: $diff"
          echo "AFFECTED=join($diff, ',')" >> "$GITHUB_OUTPUT"
      - name: Get list
        run: echo $affected
