name: CI

on: push

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    outputs:
      files: ${{ steps.get_files.outputs.AFFECTED }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Get changed files
        shell: bash
        id: get_files
        run: |
          git fetch origin main
          "DIFF=$(git diff origin/main..HEAD --name-only -- tests-examples/)" >> $GITHUB_ENV
          echo "DIFF=$DIFF"
      - name: Get list
        run: echo ${{env.DIFF}}
