name: CI

on: push

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    outputs:
      affected: ${{ steps.affected.outputs.AFFECTED }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Get changed files
        shell: bash
        id: affected
        run: |
          git fetch origin main
          AFFECTED=("$(git diff origin/main..HEAD --name-only -- tests-examples/ | grep "^.\w" | cut -c 4-)")

          echo "$AFFECTED" >> $GITHUB_OUTPUT
          echo $AFFECTED
      - name: Get list
        run: echo $affected
