name: CI

on: push

jobs:
  changed_files:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2  # OR "2" -> To retrieve the preceding commit.
      - name: Get affected project
        shell: bash
        run: |
          node scripts/aff.js
          echo $AFFECTED_PROJECT

      - name: Get changed files
        shell: bash
        run: |
          git fetch origin main
          mydiff=$(git diff origin/main..HEAD --name-only -- tests-examples/)
          echo $mydiff