name: CI

on: push

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Get changed files
        shell: bash
        id: get_files
        run: |
          changedServices=()
          while IFS= read -r line; do
          changedServices+=("${line}")
          done < <($(git diff origin/main..HEAD --name-only -- tests-examples/) | awk -F'/' 'NF!=1{print $1}' | sort -u)
      - name: Get list
        run: echo $changedServices
